#TargetName : Dependencies
#<TAB>commands

Build: project_main.c tour_manage.c
gcc project_main. tour_manage.c -o tour_manage.out

Run : Build
      ./tour_manage.out

Clean:
   em -rf *.o *.out *.i *.s